### ISSUE TITLE
DxScrollView doesn't transclude its content

### ISSUE THREAD

**Issue by dxbykov** [DevExpress/devextreme-angular2#49]
The code below doesn't work:

````html
<dx-scroll-view>
    <div>Some scrollable content</div>
</dx-scroll-view>
````

**Comment by dxbykov** [comment]
Fixed by #120

**Comment by strpipe** [comment]
I wanted to display a DxScrollView inside a DxPopUp, without luck.
I was happy to find this piece of code you posted. So I am sure I am not doing something wrong.

I find that this problem is still existing though I am not sure if I updated my project correctly. I just manually deinstalled devextreme-angular2 and typed npm install after that.

**Comment by strpipe** [comment]
I think the npm package is not updated yet, so I still encountered the problem.
I copied your files manually from the ./dist Folder to my project. It works now.
